#!/bin/bash
heroku_app=ideas-app-dev
gcp_project=ideas-app
project_id=ideas-app-276115
container=gcr.io/$project_id/$gcp_project:latest


pipenv run python manage.py generate_swagger swagger.json
mv swagger.json ../docs
cd ../docs
redoc-cli bundle swagger.json
mv redoc-static.html index.html

cd -

db_credentials=$(heroku pg:credentials:url DATABASE -a ${heroku_app} | grep dbname)

echo "DB_NAME=$(echo $db_credentials | sed 's/^.*\dbname=\([^ ]*\) .*/\1/')
DB_USER=$(echo $db_credentials | sed 's/^.*\user=\([^ ]*\) .*/\1/')
DB_PASSWORD=$(echo $db_credentials | sed 's/^.*\password=\([^ ]*\) .*/\1/')
DB_HOST=$(echo $db_credentials | sed 's/^.*\host=\([^ ]*\) .*/\1/')
DB_PORT=$(echo $db_credentials | sed 's/^.*\port=\([^ ]*\) .*/\1/')" > .env
docker build -t $container -f Dockerfile .

docker push $container

gcloud beta run deploy $gcp_project --image $container --platform managed

rm .env
